### PR TITLE
Skip calling Windows console api with piped stdin

### LINKED ISSUE #50: `read_password` fails on Windows when stdin is piped
Hi!
I ran into the following issue on Windows 10. Could be related to #49 but I'm not sure. With the `main.rs` below
```rust
fn main() {
    rpassword::read_password().unwrap();
}
```
running `echo "asd" | cargo run` results in ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "The handle is invalid." }'```.

The cause is the `GetConsoleMode` call at https://github.com/conradkleinespel/rpassword/blob/096c3522ddcd809ece27df6e4ac3ee6cfb3175ed/src/lib.rs#L184-L188 which fails because the handle has the wrong type when stdin is piped (I found this question on the topic https://comp.os.ms-windows.programmer.win32.narkive.com/xiPamaWm/getconsolemode-fails-when-input-piped). Subsequent Get/SetConsoleMode calls would also fail.

A simple solution could be to wrap the console mode calls in something like
```rust
if unsafe { winapi::um::fileapi::GetFileType(handle) } != winapi::um::winbase::FILE_TYPE_PIPE {
    // ...
}
```
but I'm not sure if there are any other implications to doing so. If this sounds acceptable, I can make a PR for it. Alternatively it could check that the handle is of type `FILE_TYPE_CHAR` (related SO answer https://stackoverflow.com/a/3453272) but I felt like making a special case for pipe would be less likely to cause any other issues.

For additional context, I originally bumped into this issue when trying to test a CLI app that asks for a password using rpassword, which tried to run the CLI with `Command::new(cli).stdin(Stdio::piped()).spawn()` and write into the stdin handle. Also, I don't really know anything about the Windows API so it's possible I've misunderstood or overlooked something. Thanks for your work on rpassword!

### PR DESCRIPTION
**Pull request by Heliozoa**
Fixes #50 

I implemented the changes discussed in the issue. I also wrote a test that fails on Windows in the current master branch and passes after the changes, but it feels a bit hacky as it just runs one of the examples...

### CODE REVIEW

**Comment by Heliozoa** [comment]
Looks like the 1.33.0 version of rustc used by appveyor doesn't understand the temporary borrow in the test. Adding braces around it like so
```rust
{
    let stdin = out.stdin.as_mut().unwrap();
    stdin.write_all("secret".as_bytes()).unwrap();
}
```
or upgrading the appveyor version to 1.44.0 (or whenever this was fixed) should fix it.

**Comment by conradkleinespel** [comment]
@Heliozoa Feel free to upgrade Rust version to 1.44 in appveyor & travis configs, that'll make things easier. If people want to upgrade, they'll just have to use 1.44 too.

**Comment by equalsraf** [comment]
:+1 on my end, and nice going on the test.

**Comment by conradkleinespel** [comment]
Awesome, thank you both! I'll go ahead and merge. Then I'll publish to crates.io. Because users need to potentially upgrade their version of Rust, it is a "breaking" change so it'll be a major version increase.

**Comment by conradkleinespel** [comment]
Just saw that there is another PR I need to merge before publishing to avoid multiple major version increases. I'll get around to doing this the coming weekend.

Until then, I encourage you to use the `git` way of defining the dependency:

```
[dependencies]
rpassword = { git = "https://github.com/conradkleinespel/rpassword", rev = "189c388" }
```

**Pull request merged**
